config/routes.rb
Rails.application.routes.draw do
  resources :tasks do
    collection do
      get 'active'
      get 'completed'
    end 
  end

  root 'tasks#index'

end

app/models/task.rb
class Task < ActiveRecord::Base
  validates :description, presence: true, length: { minimum: 6}

  def self.active
    self.all.where(completed: false)
  end

  def self.completed
    self.all.where(completed: true)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all.order(created_at: :asc)
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)

    if @task.save
      redirect_to root_path
    else
      @tasks = Task.all.order(created_at: :asc)
      flash.now[:error] = 'your description needs to be at least six characters'
      render 'index'
    end

  end

  def update
    task = Task.find(params[:id])
    task.update(completed: !task.completed)
    redirect_to root_path
  end

  def destroy
    task = Task.find(params[:id])
    task.destroy
    redirect_to root_path
  end

  def active
    @tasks = Task.active.order(created_at: :asc)
    @task = Task.new
    render 'index'
  end

  def completed
    @tasks = Task.completed.order(created_at: :asc)
    @task = Task.new
    render 'index'
  end

  private
    def task_params
      params.require(:task).permit(:description, :completed)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TodoList</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <% if !flash.now[:error].nil? %>  
    <div class = 'panel flash-area'>
      <% flash.each do |name, msg| -%>
        <p><%= content_tag :div, msg, class: name %></p>
      <% end -%>
    </div>
  <% end %>
<%= yield %>

</body>
</html>

app/views/tasks/index.html.erb
<h1>todos</h1>


<%= form_for @task do |f| %>
  <p>
  <%= f.text_field :description, placeholder: 'what needs to get done?' %>
  </p>
  <p>
  <%= f.submit %>
  </p>
<% end %>

<ul>
  <% @tasks.each do |task| %>
    <li>
    <% if task.completed == false %>
      <%= link_to 'O', task_path(task), method: 'patch' %>
    <% else %>
      <%= link_to 'Ø', task_path(task), method: 'patch' %>
    <% end %>
      <%= task.description %>
      <%= link_to 'X', task_path(task), method:'delete' %>
    </li>
  <% end %>
</ul>

<%= link_to 'active', active_tasks_path %>
<%= link_to 'completed', completed_tasks_path %>
<%= link_to 'all', root_path %>